### PR TITLE
POA module

### PR DESCRIPTION
**Pull request by tac0turtle**
- moved POA module impl from sdk into modules repo

replaces: https://github.com/cosmos/cosmos-sdk/pull/4971

Signed-off-by: Marko Baricevic <marbar3778@yahoo.com>

### CODE REVIEW

**Comment by rigelrozanski** [comment]
R4R?

**Comment by marbar3778** [comment]
nope there are a few things missing and then testing

**Comment by marbar3778** [comment]
waiting to get a response on https://github.com/cosmos/cosmos-sdk/issues/4771 before moving forward on the gentx logic.

**Comment by okwme** [comment]
😭

**Comment by tac0turtle** [comment]
> 😭

There is a team that has POA implemented. If they don't open source in a couple of weeks then ill spend two days knocking this out

**Comment by okwme** [comment]
I was meeting with a team building a rather permissioned validator set and I always think it's actually better to use the default staking module and just be careful about who has stake. Since some POA modules actually do have something like a degrading reputation it really looks a lot like the staking module except for one very important aspect: you can't transfer the staking token.

Why not make a parameter to the staking module that allows or prevents the staking token to be transferred? This would mean that you have all the nice features of staking like an offline validator will lose stake until they are no longer part of the val set.  Slashing is still helpful as it rewards the validators who are online the most without being total pay to play.

I modified the bank handler here: https://github.com/interchainberlin/pooltoy/blob/master/app/restrictedBankModule.go in order to prevent transfers to accounts that don't exist. Similar logic could be added that would prevent any staking token from being transferred via send. Then there could be another param added to staking to mint new stake to a new validator candidate after it got voted in. Or a separate module dedicated just to minting stake after a gov proposal.

Maybe I'm missing some of the other features of popular POA schemes but this could be a great hybrid that also utilizes the actual staking module to get extra features.

**Comment by okwme** [comment]
Feel like @sunnya97 would have some interesting thoughts here

**Comment by Tectract** [comment]
I'm picking up the torch here, too. For my company that does green-energy and real-estate share-tracking, and for the Government Blockchain Association.

**Pull request closed without merging**
