### PR TITLE
Add wasm module

### PR DESCRIPTION
**Pull request by ethanfrey**
This is based on a stable v0.37 cosmos-sdk tag and has all functionality tested.

The cli code was done in a copy that I used in my gaiad integration demo, but can be back-ported here if desired.

@marbar3778 happy for a review/comments or any idea how this should move forward

### CODE REVIEW

**Comment by fedekunze** [comment]
This is awesome. I’ll try review it early next week

**Comment by marbar3778** [comment]
This is super cool. looked briefly through the code, will review it on Monday. 

Is there an associated spec for the module?

**Comment by ethanfrey** [comment]
No, there is no spec for it.  There are a number of docs for the underlying wasm engine. I will add some specs soon.

Note this is on cosmos-sdk 0.37.1 and I needed to update to master to test integration with gaia. I'm kind of waiting for 0.38 to stabilize the module in a form that will (hopefully) be compatible with a tagged gaia release. So, there is a large TODO outstanding (when sdk/gaia get tagged).

**Comment by jackzampolin** [comment]
Like targeting 0.38 for this.

**Comment by marbar3778** [comment]
Would this be ready to merge as is? I see a couple todo

**Comment by ethanfrey** [comment]
@marbar3778 I had to fork gaia and use a cosmos-sdk:master  to really test this full-stack (with cli). That is in https://github.com/cosmwasm/wasmd. I can copy the module in that app back into this repo once there is a stable master (v0.38). It just has some cleanup and the cli (and querier) fully developed, internal logic is the same.

I figured I'd put it here and get some feedback. I have no idea the timeline for v0.38

**Comment by marbar3778** [comment]
talked with Ethan he mentioned that this can be closed

**Comment by ethanfrey** [comment]
Yes, anyone interested in cosmwasm, please check out https://github.com/cosmwasm/wasmd and https://www.cosmwasm.com

**Pull request closed without merging**
